# Issue 模板配置
blank_issues_enabled: false  # 禁止空白 issue (必须选模板)
contact_links:
  - name: 💬 讨论 / 问答
    url: https://github.com/PerfectZQ888/FIFA-WorldCup-2026-V2/discussions
    about: 一般问题、想法、讨论
  - name: 📖 文档
    url: https://github.com/PerfectZQ888/FIFA-WorldCup-2026-V2/blob/main/README.md
    about: 先看文档, 多数问题这里有答案
